name: Update DoH Whitelists

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '33 2 * * *'

env:
  GITHUB_REF: ${{ github.ref }}
  PYTHON_VERSION: '3'
  DOH_FILES: |
    whitelist-ip-doh-ipv4.txt
    whitelist-ip-doh-ipv6.txt

permissions:
  contents: write
  pull-requests: write

jobs:
  do-update:
    runs-on: ubuntu-24.04

    steps:
      - name: checkout repo
        uses: actions/checkout@v6
        with:
          repository: ${{ github.repository }}
          ref: ${{ env.GITHUB_REF }}
          fetch-depth: 0
          persist-credentials: true

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: run update script
        run: python whitelist-ip-doh.py

      - name: Check if any files were updated
        uses: tj-actions/verify-changed-files@v20.0.4
        id: verify-changed-files
        with:
          files: ${{ env.DOH_FILES }}

      - name: generate unique branch name for update
        id: branch-name
        run: |
          echo "NAME=$(date +gh-doh-%Y%m%d%H%M%S)" >> "$GITHUB_OUTPUT"

      - name: create the new doh branch
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: git checkout -b ${{ steps.branch-name.outputs.NAME }}

      - name: Git Auto Commit
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: automated doh ip whitelist update
          branch: ${{ steps.branch-name.outputs.NAME }}
          file_pattern: ${{ env.DOH_FILES }}

      - name: Create the PR
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: gh pr create -B master -H ${{ steps.branch-name.outputs.NAME }} --title 'Merge ${{ steps.branch-name.outputs.NAME }} into master' --body 'Automated doh whitelist update'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
